	
This notebook contains code and concepts from the "Introduction to Deep Learning with PyTorch" course on DataCamp, originally developed by Maham Khan.

I have added extra comments, explanations, and modifications to the code to aid understanding and provide additional context.

## First Neural Network


In [4]:
import torch
import torch.nn as nn
## Create input
# tensor with three features
input_tensor = torch.tensor(
[[0.3471, 0.4547, -0.2356]])

# Define our first linear layer
linear_layer = nn.Linear(in_features=3, out_features=2)

# Pass input through linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[-0.6192,  0.0019]], grad_fn=<AddmmBackward0>)


In [5]:
# Print the weight and bias of the linear layer
print("linear_layer.weight: ", linear_layer.weight)
print("linear_layer.bias: ", linear_layer.bias)

linear_layer.weight:  Parameter containing:
tensor([[ 0.1637, -0.4926, -0.2364],
        [ 0.2856, -0.4685, -0.3842]], requires_grad=True)
linear_layer.bias:  Parameter containing:
tensor([-0.5078,  0.0252], requires_grad=True)


### Linear Layer operation 

For input $X$, with weights $W_0$ and bias $b_0$, the linear layer operation is:

$y_0 = W_0 * X + b_0$

- weights $W_0$ and bias $b_0$ are randomly initialized 
- $y_0$ is the output of the linear layer
- tuning the weights and biases is the process of training the model
- weights and biases are adjusted to minimize the loss function
- the loss function measures how well the model's predictions match the actual data


In [ ]:
# Pass input through linear layer again
output = linear_layer(input_tensor)
print(output)

In [12]:
# Random values from normal distribution (mean=0, std=1)
input_tensor = torch.randn(10) 

# Create network with three linear layers
model = nn.Sequential(
    nn.Linear(10, 18),
    nn.Linear(18, 20),
    nn.Linear(20, 5)
)

# Pass input through model
output = model(input_tensor)
print(output)   

tensor([ 0.1147,  0.1996, -0.4057,  0.1150, -0.1326], grad_fn=<ViewBackward0>)


In [11]:
# Batch of 32 samples, each with 10 features
batch_tensor = torch.randn(32, 10)  # Shape: (batch_size, features)

# Shape of batch tensor
batch_tensor.shape

# First 5 samples in the batch
batch_tensor[:5]

tensor([[-1.8262, -1.5991, -0.5800,  1.0755,  0.2274,  1.1292, -0.2907,  1.3053,
          1.3232,  0.6945],
        [ 1.5327, -0.4081,  0.1420, -1.3438,  1.7942,  0.4449, -1.1740, -0.0416,
          0.7742,  0.5491],
        [ 0.3964,  0.7389,  0.4995, -1.7049, -1.7698,  0.2849, -0.1710, -1.2045,
         -1.2469, -0.1376],
        [-0.4337, -0.0896,  0.0887, -0.3950, -0.3887, -1.7668,  1.2882, -0.8495,
          0.7437, -0.7374],
        [-0.3934,  1.6661,  0.1323, -1.9737,  2.4621, -0.8096,  1.9039,  1.2751,
         -0.8228,  0.1221]])

In [ ]:
# Sigmoid function
# Sigmoid function is equivalent to logistic regression when it is used as the last layer of a neural network
input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

model = nn.Sequential(
    nn.Linear(6, 4), # First linear layer
    nn.Linear(4, 1), # Second linear layer
    nn.Sigmoid() # Sigmoid activation function
)

# Pass input through model
output = model(input_tensor)
print(output)
